### ISSUE TITLE
'http://borcteam.bplaced.net/en/javainstaller.php' response 404

### ISSUE THREAD

**Issue by Lyon1994** [julianwi/javainstaller#8]
could you help me?
I want to run a *.jar application without GUI(like websocket)  on Android device
I find this project,but it isn't working

**Comment by julianwi** [comment]
The server is currently down. I already contacted the bplaced support. Try again in a few days.

**Comment by Lyon1994** [comment]
thank you！
谢谢！

**Comment by julianwi** [comment]
the bplaced account is disabled until Feb 07 due to inactivity

**Comment by julianwi** [comment]
The server is online again now.
